In [1]:
import numpy as np

In [2]:
price_vector = np.array([1, 10, 11, 12, 13, 14, 15])
initial_value = 100

In [3]:
num_of_days = len(price_vector)
matrix = np.zeros((num_of_days, num_of_days))
matrix[0, 0] = 1
matrix[1:, 0] = -initial_value
matrix

array([[   1.,    0.,    0.,    0.,    0.,    0.,    0.],
       [-100.,    0.,    0.,    0.,    0.,    0.,    0.],
       [-100.,    0.,    0.,    0.,    0.,    0.,    0.],
       [-100.,    0.,    0.,    0.,    0.,    0.,    0.],
       [-100.,    0.,    0.,    0.,    0.,    0.,    0.],
       [-100.,    0.,    0.,    0.,    0.,    0.,    0.],
       [-100.,    0.,    0.,    0.,    0.,    0.,    0.]])

In [5]:
np.diag_indices_from(matrix)

(array([0, 1, 2, 3, 4, 5, 6]), array([0, 1, 2, 3, 4, 5, 6]))

In [10]:
np.tril_indices_from(matrix)[1]

array([0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0,
       1, 2, 3, 4, 5, 6])

In [ ]:
matrix[np.diag_indices_from(matrix)[0][1:], np.diag_indices_from(matrix)[1][1:]] = price_vector[1:]
matrix

In [ ]:
matrix[np.triu_indices_from(matrix, 1)[0], np.triu_indices_from(matrix, 1)[1]] = np.diff(price_vector)
gram_matrix = self.matrix.T @ self.matrix